--liquibase formatted.sql
--changeset michael.cawayan:ESP_USER.SAS_AFF_PREDIAL_JOURNAL contextFilter:PH endDelimiter:/ runOnChange:true

ALTER TABLE "ESP_USER"."SAS_AFF_PREDIAL_JOURNAL" 
  DROP (
    RESPTRACKING_CD_TBD
,PROCESSED_FLG
,PROCESSED_DTTM
,DATE_EFFECTIVE
,COMMUNICATION_CD
,CH_ID
,ID_CUID
,UPDATE_DTTM
,DEACT_ID
,RESPTRACKING_CD
,DEACTIVATION_REASON_ID
,LOG_ACTION_ID
,SEEDLIST_FLG
,CALL_SOURCE
) 
/
ALTER TABLE "ESP_USER"."SAS_AFF_PREDIAL_JOURNAL" 
  ADD (
  ExternalSystem varchar2(20 CHAR)
 ,Origin varchar2(20 CHAR)
)
/
