--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.SAS_AFF_PREDIAL_JOURNAL contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
  CREATE TABLE "INT_COMMUNICATION"."SAS_AFF_PREDIAL" (
    "IL_COMMUNICATION_ID" NUMBER(38,0), "RESPTRACKING_CD_TBD" VARCHAR2(19 CHAR), "PROCESSED_FLG" NUMBER, "PROCESSED_DTTM" DATE, "DATE_EFFECTIVE" DATE, "COMMUNICATION_CD" VARCHAR2(30 CHAR), "CH_ID" NUMBER, "ID_CUID" NUMBER, "UPDATE_DTTM" DATE, "DEACT_ID" NUMBER(38,0), "RESPTRACKING_CD" VARCHAR2(19 CHAR), "DEACTIVATION_REASON_ID" NUMBER, "CREATED_DTTM" DATE, "LOG_ACTION_ID" NUMBER, "SEEDLIST_FLG" NUMBER(1,0), "BLACKLIST_PATTERN" VARCHAR2(20 CHAR), "CALL_SOURCE" VARCHAR2(250 CHAR), "VALID_TO" DATE,  
  CONSTRAINT "SAS_AFF_PREDIAL_PK" PRIMARY KEY ("DEACT_ID") USING INDEX  ENABLE
  ) 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO SAS_INT_COMMUNICATION_RO
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO MA_TEMP
/
GRANT SELECT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO HCPH_INT_COMMUNICATION_RO
/
GRANT SELECT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO GB_INT_COMM_RO
/
GRANT SELECT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO INT_ETL
/
GRANT SELECT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO HCI_APP_SELECT
/
GRANT UPDATE ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO HCI_APP_UPDATE
/
GRANT SELECT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO HCI_RO_INT_COMMUNICATION
/
GRANT INSERT ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON "INT_COMMUNICATION"."SAS_AFF_PREDIAL" TO APPSUPPORT
/